config/routes.rb
Rails.application.routes.draw do
  root 'mains#index' 
  get '/about' => 'mains#about'
  get '/events' => 'mains#events'
  get '/contact' => 'mains#contact'

  get 'books/' => 'books#index' 
  get 'authors/' => 'authors#index'

  get 'books/new' => 'books#new', as: :new_book
  get 'authors/new' => 'authors#new', as: :new_author

  get 'books/:id' => 'books#show', as: :book
  get 'authors/:id'=> 'authors#show', as: :author

  post 'books/' => 'books#create'
  post 'authors/' => 'authors#create'
  
  get 'books/:id/edit' => 'books#edit', as: :edit_book
  get 'authors/:id/edit' => 'authors#edit', as: :edit_author

  patch 'books/:id' => 'books#update'
  patch 'authors/:id' => 'authors#update'

  delete 'books/:id' => 'books#destroy'
  delete 'authors/:id' => 'authors#destroy'

end

app/models/author.rb
class Author < ActiveRecord::Base
	has_many :books

  def full_name
    "#{f_name} #{l_name}"
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :author
	has_one :author
end

app/models/main.rb
class Main < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
  	@authors = Author.all.order("l_name")
  end
  
  def show
  	@author = Author.find(params[:id])
  	@book_array = Book.where("author_id = ?", @author)
    @books = @book_array.map{ |x| {name: x.title, id: x.id} }
  end
  

  def new
  	@author = Author.new
  end

  def edit
  	@author = Author.find(params[:id])
  end

  def create 
  	@author = Author.new(author_params)
  	if @author.save
  		redirect_to authors_path
  	else
  		render :new
  	end
  end

  def update
  	@author = Author.find(params[:id])
  	if @author.update_attributes(author_params)
  		redirect_to authors_path
  	else
  		render :edit
  	end
  end

   private
	def author_params
		params.require(:author).permit(:f_name, :l_name, :dob, :deceased)
	end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
  	@books = Book.all.order("author_id")
  end

  def show
  	@books = Book.all
  	@book = Book.find(params[:id])
  	@authors = Author.all
  end

  def create 
  	@book = Book.new(book_params)
  	if @book.save
  		redirect_to books_path
  	else 
  		render :new
  	end
  end

  def new
  	@book = Book.new
  	@authors = Author.all
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update_attributes(book_params)
  		redirect_to book_path
  	else
  		render :edit
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path
  end

  private
	def book_params
		params.require(:book).permit(:title, :author_id, :copyright, :publisher, :desc, :language, :isbn)
	end



end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
  def index
    @books = Book.take(10)
    @authors = Author.take(10)

    #some other options...

    # the below code will change the layout for the mains#index page
    # render layout: "application2.html.erb"

    # this will render an alternative index page named alt_index
    # render :alt_index

  end

  def about
  end

  def events
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def active_class(link_path)
		current_page?(link_path) ? "active" : ""
		# request.fullpath == link_path ? "active" : ""
	end

end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/views/authors/edit.html.erb
<div class="main_content">
	<h2>Edit Author</h2>
	<%= form_for @author do |f| %>
			<p>
			Author's First Name: <%= f.text_field :f_name %> <br><br>
			Author's Last Name: <%= f.text_field :l_name %> <br><br>
			DOB: <%= f.date_select :dob %><br><br> 
			Living?: <%= check_box_tag(:deceased) %><br><br>
		<%= f.submit "Save Changes" %></p>
		<% end %>											
</div>

app/views/authors/index.html.erb
<div class="main_content">
	<h2>See All Authors</h2>	
	<% @authors.each do |author| %>
	<% fullname = author.f_name + " " + author.l_name %>

	<li><%= link_to fullname, author %></li>

	<% end %>	

	<li><strong><%= link_to "Add New Author", new_author_path %></strong></li>											
</div>

app/views/authors/new.html.erb
<div class="main_content">
	<h2>Add New Author</h2>	

	<%= form_for @author do |f| %>
			<p>
			Author's First Name: <%= f.text_field :f_name %> <br><br>
			Author's Last Name: <%= f.text_field :l_name %> <br><br>
			DOB: <%= f.date_select :dob %><br><br> 
			Living?: <%= check_box_tag(:deceased) %><br><br>
		<%= f.submit "Add Author" %></p>
		<% end %>											
</div>

app/views/authors/show.html.erb
<div class="main_content">
	<h2> <%= @author.full_name %> </h2>

	<p>Born: <%= @author.dob %></p>

	<p>Books by this Author:<br> <% @books.each do |x| %> 
		<li><%= link_to x[:name], book_path(x) %></li> <% end %> 
		<li><strong><%= link_to "Add Book", new_book_path %></strong></li></p>

	<p class="bottom_links"><strong><%= link_to "Back to All Authors", authors_path %> 
		<%= link_to "Edit this Author", edit_author_path %>
		<%= link_to "Delete this Author", author_path, method: :delete, data: { confirm: "Confirm Delete? You cannot undo this task!"} %></strong>
	</p>

</div>

app/views/books/edit.html.erb
<div class="main_content">
	<h2>Edit Book Details</h2>	
	<%= form_for @book do |f| %>
   	<div id="entry">
		<p>Book Title: <%= f.text_field :title %> <br><br>
		Author: <%= f.collection_select(:author_id, Author.all, :id, :full_name) %><br>
		<span style="font-size: 12px; color: red">*Don't see who you're looking for? Click <%= link_to "HERE", new_author_path %> to add an author</span><br><br>
		Publisher: <%= f.text_field :publisher %><br><br>
		Copyright: <%= f.number_field :copyright %><br><br>
		Language: <%= f.text_field :language %><br><br>
		ISBN: <%= f.number_field :isbn %><br><br>
		Description: <br><%= f.text_area :desc, size: "80x15" %><br><br></p>
	 </div>

	 <%= f.submit "Update Book Details" %>
	 <% end %>

</div>

app/views/books/index.html.erb
<div class="main_content">
	<h2>See All Books</h2>

	<% @books.each do |f| %>
	<li><%= link_to f.title, f %></li>
	<% end %>
	<li><strong><%= link_to "Add Book", new_book_path %></strong></li>

</div>

app/views/books/new.html.erb
<div class="main_content">
	<h2>Add a New Book!</h2>
	<p><%= form_for @book do |f| %>
   	<div id="entry">
		<p>Book Title: <%= f.text_field :title %> <br><br>
		Author: <%= f.collection_select(:author_id, Author.all, :id, :full_name) %><br>
		<span style="font-size: 12px; color: red">*Don't see who you're looking for? Click <%= link_to "HERE", new_author_path %> to add an author</span><br><br>
		Publisher: <%= f.text_field :publisher %><br><br>
		Copyright: <%= f.number_field :copyright %><br><br>
		Language: <%= f.text_field :language %><br><br>
		ISBN: <%= f.number_field :isbn %><br><br>
		Description: <br><%= f.text_area :desc, size: "80x15" %><br><br>
	 </div>

	 <%= f.submit "Add New Book" %>
	 <% end %>
	</p>
</div>

app/views/books/show.html.erb
<div class="main_content">
	<h2> <%= @book.title %> </h2>

	<% this_author = @authors.find(@book.author_id) %>

	<p><strong>Author:</strong> <%= link_to this_author.f_name+" "+this_author.l_name, author_path(@book.author_id) %></p>

	<p><strong>About This Book:</strong> <%= @book.desc %> </p>

	<p><strong>Published by:</strong> <%= @book.publisher %> (<%= @book.copyright %>)</p>
	<p><strong>Language(s) Available:</strong> <%= @book.language %> </p>
	<p><strong>ISBN:</strong> <%= @book.isbn %> </p>
	<p class="bottom_links"><strong><%= link_to "See All Books...", books_path %><span width="25px"></span>
		<%= link_to "Edit this Book...", edit_book_path %>
		<%= link_to "Delete this Book...", book_path, method: :delete, data: { confirm: "Confirm Delete? You cannot undo this task!" } %></strong>
	</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Public Library</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>The Public Library</h1>
	<hr />
	
	<div class="aside">
		<%= image_tag("logo.jpg") %><br>
		<%= link_to "HOME", root_path %><br>
		<%= link_to "ABOUT", about_path %><br>
		<%= link_to "BOOKS", books_path %><br>
		<%= link_to "AUTHORS", authors_path %><br> 
		<%= link_to "EVENTS", events_path %><br>
		<%= link_to "CONTACT", contact_path %><br>
	</div>

<%= yield %>

<footer>
		Labor Day Weekend Project By: Juli Emmel
</footer>

</body>
</html>

app/views/mains/_header.html.erb
<header><h1>This is an alternate header!!</h1></header>

app/views/mains/about.html.erb
<div class="main_content">
	<h2>About your Public Library</h2>	
	<p><strong>Address:</strong> 1234 Little Book Road, Los Angeles, CA 90065<br><br>
		<strong>Hours:</strong> Open Daily 8am - 8pm<br><br>
		<strong>Parking:</strong> Free parking is available to library patrons<br><br>
		<strong>Need more info?</strong> Contact us!
</div>

app/views/mains/alt_index.html.erb
<h1>I'm an alternative index page!!!!</h1>

app/views/mains/contact.html.erb
<div class="main_content">
	<h2>Contact your Public Library</h2>	
	<p><strong>Address:</strong> 1234 Little Book Road, Los Angeles, CA 90065<br><br>
		<strong>Hours:</strong> Open Daily 8am - 8pm<br><br>
		<strong>Phone:</strong> 213-740-1862<br><br>
		<strong>Email:</strong> info@thepubliclibrary.org</p>
</div>

app/views/mains/events.html.erb
<div class="main_content">
	<h2>Contact your Public Library</h2>	
	<p>Check back soon for upcoming events!</p>
</div>

app/views/mains/index.html.erb
<div class="main_content">
	<h2 style="padding-right: 150px;">Welcome to your Public Library Online!</h2>	
	<div style="float: left; margin-right: 50px; width: 30%">
		<h2>Browse Books</h2>
		<% @books.each do |f| %>
		<li><%= link_to f.title, book_path(f) %></li> 
		<% end %>
		<p style="text-align: center"><strong>
			<%= link_to "See All Books...", books_path %></strong></p>
	</div>
	
	<div style="float: left; width: 30%">
		<h2>Browse Authors</h2>
		<% @authors.each do |f| %>
		<% full_name = f.f_name + " " + f.l_name %>
		<li><%= link_to full_name, author_path(f) %></li> 
		<% end %>		
		<p style="text-align: center"><strong>
			<%= link_to "See All Authors...", authors_path %></strong></p>
	</div>
</div>

app/views/shared/_header.html.erb
<header><h1>This is an alternate header!!</h1></header>